services:
  app:
    container_name: frontend
    image: frontend-messenger
    tty: true
    ports:
      - 5173:5173
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
      - .env.development
    networks:
      - frontend-network
    volumes:
      - .:/var/www/app
      - node_modules:/var/www/app/node_modules
    
networks:
  frontend-network:
    driver: bridge

volumes:
  node_modules:
    driver: local 
    driver_opts:
      type: none
      o: bind
      device: ./node_modules