services:
  frontend:
    container_name: frontend
    image: "frontend.messenger"
    networks:
      - frontend
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    tty: true

networks:
  frontend:
    driver: bridge
